services:
  artes-service:
    build: ./artes-service
    container_name: artes-service
    restart: unless-stopped
    ports:
      - "4010:4010"
    volumes:
      - ./src/temp:/usr/src/app/src/temp
    depends_on:
      - db
      - minio

  artes-ui:
    build: ./artes-ui
    container_name: artes-ui
    restart: unless-stopped
    ports:
      - "4009:4009"
    depends_on:
      - artes-service

  db:
    image: ./artes-db
    container_name: artes-db
    environment:
      POSTGRES_DB: artes_reports
      POSTGRES_USER: artes
      POSTGRES_PASSWORD: artes
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: artes-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: artes
      MINIO_ROOT_PASSWORD: artes123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 artes artes123 &&
      mc mb -p local/artes-reports
      "

volumes:
  pg_data:
  minio_data:
